export const conditionPages = [
  {
    slug: 'baignade-ideale',
    titleMq: 'Plages parfaites pour la baignade aujourd\u2019hui \u2014 Martinique',
    titleGp: 'Plages parfaites pour la baignade aujourd\u2019hui \u2014 Guadeloupe',
    h1Mq: 'Les meilleures plages pour la baignade aujourd\u2019hui en Martinique',
    h1Gp: 'Les meilleures plages pour la baignade aujourd\u2019hui en Guadeloupe',
    intro: 'Ces plages combinent aujourd\u2019hui un \u00e9tat sargasses propre, une mer calme et une eau chaude. Id\u00e9al pour une sortie en famille, un bain prolong\u00e9 ou des vacanciers peu habitu\u00e9s aux courants caribbean.',
    filter: (b, w) => b.status === 'clean' && w && w.condition === 'calm',
    fallback: 'Aucune plage ne r\u00e9unit aujourd\u2019hui les trois crit\u00e8res id\u00e9aux (propre + mer calme + eau chaude). Consultez la carte pour identifier le meilleur compromis du moment.',
  },
  {
    slug: 'mer-calme',
    titleMq: 'Plages avec mer calme aujourd\u2019hui \u2014 Martinique',
    titleGp: 'Plages avec mer calme aujourd\u2019hui \u2014 Guadeloupe',
    h1Mq: 'Plages avec mer calme en Martinique aujourd\u2019hui',
    h1Gp: 'Plages avec mer calme en Guadeloupe aujourd\u2019hui',
    intro: 'Donn\u00e9es marines Open-Meteo mises \u00e0 jour quotidiennement. Une mer calme (vagues inf\u00e9rieures \u00e0 0,8\u00a0m) facilite la baignade avec de jeunes enfants, le snorkeling et le paddle. Les conditions peuvent changer rapidement\u00a0: v\u00e9rifiez la fiche d\u00e9taill\u00e9e de chaque plage avant de partir.',
    filter: (b, w) => w && (w.condition === 'calm' || (w.waveHeight != null && w.waveHeight < 0.8)),
    fallback: 'Aucune plage ne pr\u00e9sente une mer calme aujourd\u2019hui. La houle est g\u00e9n\u00e9ralis\u00e9e \u2014 optez plut\u00f4t pour des spots abrit\u00e9s c\u00f4te sous-le-vent.',
  },
  {
    slug: 'mer-agitee',
    titleMq: 'Plages avec mer agit\u00e9e aujourd\u2019hui \u2014 Martinique (surf, bodyboard)',
    titleGp: 'Plages avec mer agit\u00e9e aujourd\u2019hui \u2014 Guadeloupe (surf, bodyboard)',
    h1Mq: 'Plages avec mer agit\u00e9e en Martinique aujourd\u2019hui',
    h1Gp: 'Plages avec mer agit\u00e9e en Guadeloupe aujourd\u2019hui',
    intro: 'Pour les surfeurs, bodyboarders et longboarders qui cherchent de la vague. Mais attention\u00a0: ces conditions sont d\u00e9conseill\u00e9es aux enfants et aux baigneurs occasionnels. V\u00e9rifiez le drapeau de baignade sur place.',
    filter: (b, w) => w && (w.condition === 'rough' || (w.waveHeight != null && w.waveHeight >= 1.5)),
    fallback: 'Aucune plage n\u2019affiche une mer agit\u00e9e aujourd\u2019hui. Conditions tr\u00e8s plates \u2014 revenez demain.',
  },
  {
    slug: 'uv-fort',
    titleMq: 'Plages avec UV tr\u00e8s fort aujourd\u2019hui \u2014 Martinique (prot\u00e9gez-vous)',
    titleGp: 'Plages avec UV tr\u00e8s fort aujourd\u2019hui \u2014 Guadeloupe (prot\u00e9gez-vous)',
    h1Mq: 'Indice UV tr\u00e8s fort aujourd\u2019hui en Martinique',
    h1Gp: 'Indice UV tr\u00e8s fort aujourd\u2019hui en Guadeloupe',
    intro: 'Un indice UV sup\u00e9rieur ou \u00e9gal \u00e0 9 correspond \u00e0 un risque tr\u00e8s \u00e9lev\u00e9 de coup de soleil en moins de 15 minutes sans protection. \u00c9vitez l\u2019exposition entre 11\u00a0h et 15\u00a0h, utilisez un \u00e9cran solaire SPF 50, portez chapeau et t-shirt anti-UV pour les enfants.',
    filter: (b, w) => w && w.uvMax != null && w.uvMax >= 9,
    fallback: 'L\u2019indice UV est mod\u00e9r\u00e9 partout aujourd\u2019hui \u2014 conditions plus souples pour la journ\u00e9e \u00e0 la plage.',
  },
  {
    slug: 'plages-enfants',
    titleMq: 'Plages adapt\u00e9es aux enfants aujourd\u2019hui \u2014 Martinique',
    titleGp: 'Plages adapt\u00e9es aux enfants aujourd\u2019hui \u2014 Guadeloupe',
    h1Mq: 'Plages id\u00e9ales pour les enfants en Martinique aujourd\u2019hui',
    h1Gp: 'Plages id\u00e9ales pour les enfants en Guadeloupe aujourd\u2019hui',
    intro: 'S\u00e9lection de plages adapt\u00e9es aux enfants\u00a0: eau peu profonde, mer calme et sans sargasses. Parfait pour que les plus petits s\'amusent en toute s\u00e9curit\u00e9 sous surveillance.',
    filter: (b, w) => b.status === 'clean' && b.kids && w && (w.condition === 'calm' || (w.waveHeight != null && w.waveHeight < 0.8)),
    fallback: 'Aucune plage adapt\u00e9e aux enfants et propre n\u2019est disponible aujourd\u2019hui. Privil\u00e9giez les piscines ou les anses tr\u00e8s abrit\u00e9es.',
  },
  {
    slug: 'snorkeling',
    titleMq: 'Meilleurs spots de snorkeling aujourd\u2019hui \u2014 Martinique',
    titleGp: 'Meilleurs spots de snorkeling aujourd\u2019hui \u2014 Guadeloupe',
    h1Mq: 'O\u00f9 faire du snorkeling en Martinique aujourd\u2019hui',
    h1Gp: 'O\u00f9 faire du snorkeling en Guadeloupe aujourd\u2019hui',
    intro: 'D\u00e9couvrez la richesse des fonds marins antillais. Ces spots de snorkeling (racks rocheux, herbiers, barri\u00e8re de corail) combinent aujourd\u2019hui une eau propre et une mer peu agit\u00e9e pour une visibilit\u00e9 optimale.',
    filter: (b, w) => b.status === 'clean' && b.snorkel && w && (w.condition === 'calm' || (w.waveHeight != null && w.waveHeight < 1.0)),
    fallback: 'Aucun spot de snorkeling avec une bonne visibilit\u00e9 et sans sargasses n\u2019est disponible aujourd\u2019hui. La mer peut \u00eatre agit\u00e9e ou trouble.',
  }
];
