const { emailHash, emailDomain } = require('./scripts/automation/lib/email-hash.cjs');
const email1 = 'contact@diamantlesbains.com';
const email2 = 'admin@anoli-lodges.com';
console.log('email1:', email1);
console.log('hash1:', emailHash(email1));
console.log('domain1:', emailDomain(email1));
console.log('');
console.log('email2:', email2);
console.log('hash2:', emailHash(email2));
console.log('domain2:', emailDomain(email2));