/**
 * Utility functions for the sargagame project.
 * Auto-generated by AI-Factory autonomous coding test.
 */
export function calculateScore(a, b) {
  // Simple deterministic score calculation
  return { sum: a + b, difference: Math.abs(a - b), product: a * b };
}

/**
 * Format a date string to YYYY-MM-DD format
 * @param {string|Date} date - The date to format
 * @returns {string} Formatted date string
 */
export function formatDate(date) {
  const d = new Date(date);
  return d.toISOString().split('T')[0];
}

/**
 * Add days to a date and return the resulting date string (YYYY-MM-DD)
 * @param {string|Date} date - The original date
 * @param {number} days - Number of days to add (can be negative)
 * @returns {string} Resulting date string in YYYY-MM-DD format
 */
export function addDays(date, days) {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

/**
 * Check if a number is within a range (inclusive)
 * @param {number} n - The number to check
 * @param {number} min - Minimum value
 * @param {number} max - Maximum value
 * @returns {boolean} true if n is within [min, max]
 */
function isInRange(n, min, max) {
  return n >= min && n <= max;
}

export { isInRange };
