#!/usr/bin/env node
/**
 * scope-guard.cjs — Git scope validation and branch isolation
 * 
 * Ensures changes stay within declared scope. Prevents scope creep.
 * 
 * Usage:
 *   node scripts/autopilot/lib/scope-guard.cjs --scope "src/Sargasses_PROD.jsx" --verify
 *   node scripts/autopilot/lib/scope-guard.cjs --scope "src/*,tests/*" --create-branch fix/region-filter
 *   node scripts/autopilot/lib/scope-guard.cjs --verify-pr 42
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '../../..');

function run(cmd, cwd = ROOT) {
  return execSync(cmd, { cwd, encoding: 'utf-8', stdio: 'pipe' }).trim();
}

function runSafe(cmd, cwd = ROOT) {
  try { return { ok: true, out: run(cmd, cwd) }; }
  catch (e) { return { ok: false, out: e.stdout?.toString() + e.stderr?.toString() + e.message }; }
}

function parseScope(scopeStr) {
  // Parse comma-separated glob patterns
  return scopeStr.split(',').map(s => s.trim()).filter(Boolean);
}

function getChangedFiles(base = 'main') {
  const out = run(`git diff --name-only ${base}...HEAD`);
  return out.split('\n').filter(Boolean);
}

function getDiffFiles(base = 'main', target = 'HEAD') {
  const out = run(`git diff --name-only ${base}...${target}`);
  return out.split('\n').filter(Boolean);
}

function filesMatchScope(files, scopePatterns) {
  if (!scopePatterns.length) return { ok: true, violations: [] };
  
  const violations = [];
  for (const file of files) {
    const matched = scopePatterns.some(pattern => {
      if (pattern.endsWith('/*')) {
        const prefix = pattern.slice(0, -2);
        return file.startsWith(prefix + '/') || file === prefix;
      }
      if (pattern.includes('*')) {
        const regex = new RegExp('^' + pattern.replace(/\*/g, '.*') + '$');
        return regex.test(file);
      }
      return file === pattern || file.startsWith(pattern + '/');
    });
    if (!matched) violations.push(file);
  }
  return { ok: violations.length === 0, violations };
}

function getCurrentBranch() {
  return runSafe('git branch --show-current').out || 'unknown';
}

function createWorktree(branchName, baseBranch = 'main') {
  const worktreePath = path.join(ROOT, `../worktrees/${branchName.replace(/[^a-zA-Z0-9_-]/g, '_')}`);
  
  if (fs.existsSync(worktreePath)) {
    // Clean existing worktree
    runSafe(`git worktree remove --force ${worktreePath}`);
  }
  
  fs.mkdirSync(path.dirname(worktreePath), { recursive: true });
  
  const result = runSafe(`git worktree add ${worktreePath} ${baseBranch}`);
  if (!result.ok) {
    throw new Error(`Failed to create worktree: ${result.out}`);
  }
  
  return worktreePath;
}

function createBranch(branchName, baseBranch = 'main') {
  const currentBranch = getCurrentBranch();
  
  // Ensure we're on base branch
  runSafe(`git checkout ${baseBranch}`);
  runSafe(`git pull origin ${baseBranch}`);
  
  // Create and switch to new branch
  runSafe(`git checkout -b ${branchName}`);
  
  return branchName;
}

function commitChanges(scope, message, files) {
  // Stage only files within scope
  const scopePatterns = parseScope(scope);
  const { ok, violations } = filesMatchScope(files, scopePatterns);
  
  if (!ok) {
    throw new Error(`Files outside scope: ${violations.join(', ')}`);
  }
  
  runSafe(`git add ${files.join(' ')}`);
  runSafe(`git commit -m "${message}"`);
  
  return run('git rev-parse HEAD');
}

function pushBranch(branchName) {
  return runSafe(`git push -u origin ${branchName}`);
}

function createPR(title, body, baseBranch = 'main') {
  const prBody = `${body}\n\n---\nAuto-generated by factory automation.`;
  
  const result = runSafe(`gh pr create --title "${title}" --body "${prBody}" --base ${baseBranch}`);
  
  if (!result.ok) {
    throw new Error(`Failed to create PR: ${result.out}`);
  }
  
  // Extract PR number from output
  const match = result.out.match(/#(\d+)/);
  return match ? parseInt(match[1]) : null;
}

function validatePRScope(prNumber) {
  const files = runSafe(`gh pr diff ${prNumber} --name-only`).out;
  if (!files) return { ok: false, error: 'No files in PR' };
  
  const changedFiles = files.split('\n').filter(Boolean);
  return changedFiles;
}

async function main() {
  const args = process.argv.slice(2);
  
  const scope = args.find(a => a.startsWith('--scope='))?.split('=')[1];
  const verify = args.includes('--verify');
  const createBranchFlag = args.includes('--create-branch');
  const branchName = args.find(a => a.startsWith('--branch='))?.split('=')[1];
  const verifyPR = args.find(a => a.startsWith('--verify-pr='))?.split('=')[1];
  
  if (verify && scope) {
    // Verify current working tree changes against scope
    const files = getChangedFiles();
    const scopePatterns = parseScope(scope);
    const { ok, violations } = filesMatchScope(files, scopePatterns);
    
    console.log('=== Scope Verification ===');
    console.log(`Scope: ${scope}`);
    console.log(`Changed files: ${files.length}`);
    
    if (ok) {
      console.log('✅ All changes within scope');
      process.exit(0);
    } else {
      console.error('❌ Scope violations:');
      violations.forEach(v => console.error(`  - ${v}`));
      process.exit(1);
    }
  }
  
  if (verifyPR) {
    const files = validatePRScope(verifyPR);
    console.log(`PR #${verifyPR} files: ${files.length}`);
    console.log(files.join('\n'));
  }
  
  if (createBranchFlag && branchName) {
    const branch = createBranch(branchName);
    console.log(`Created branch: ${branch}`);
  }
}

if (require.main === module) {
  main().catch(e => {
    console.error('❌ Error:', e.message);
    process.exit(1);
  });
}

module.exports = {
  parseScope,
  getChangedFiles,
  getDiffFiles,
  filesMatchScope,
  getCurrentBranch,
  createWorktree,
  createBranch,
  commitChanges,
  pushBranch,
  createPR,
  validatePRScope,
  run,
  runSafe
};